### ISSUE TITLE
some mistakes

### ISSUE THREAD

**Issue by darielli** [stormbroken/Class-Notes#2]
## 关于COA19的错误
* lecture04

  * 2.6 “两个正数相加不可能暨移除，并且结果是个正数。” “暨移除”是打错的“**溢出**”？即便是溢出，这句话也有问题呀

  * booth算法 算法问题部分**插图“img/cpt4/cpt4-13.png”（右下角有数字106那张）有误**，应为“http://freezer712.top/note_pictures/cpt4_pic1.png”

  

* lecture07
  * 3.2.1.ROM 3的第二小点 “Possible to read a ROM but not possible to write new data(POM可以被读出但是不可以被写入)”  括号中“**POM**”应为“**ROM**”

* lecture08 
  * 1.3.2.3.2时间局限性的中文解释值得商榷，时间局限性强调的是“**reuse**”，即对一个数据在不同时段的重复使用，可以解释为重用，而空间局限性强调应该的是“**relatively close storage locations**”，即使用紧邻存储位置的数据而非强调重用，翻译为“在相对较短的空间内重读使用特定数据或者资源”我认为不是很合适，“重读”尤其不合适，英语的含义更接近“（连续）使用存储地址相对较近的数据”，接下来的“**Sequential locality**”也是强调类似一维数组“data elements are arranged and accessed linearly”
  * 1.3.2 ”移动块状结构“部分“在Cache中用Tag记录每一个块的**快号**，而并不是具体的地址。”快号”应为“**块号**”
  * 2.3.2 “直接映射”   1.中文解释有误，“前几个块放在一行。” 内存的一个块对应cache一行，每行按顺序对应一块，line用完后再从第0行往后放，也只有这样才可以用取模判断所在的cache 行。例如16块4行，0,4,8,12块对应0行，1,5,9,13块对应1行，以此类推。（参考文章https://www.cnblogs.com/east1203/p/11572500.html ，PPT截图http://freezer712.top/note_pictures/cpt8_pic1.png ）
  * tips 2.3 是“放置策略”，2.3.2是“Direct Mapping(直接映射)”   2.4是“全关联映射”  2.5是“组相联映射”，目录不对应
  * 另，2.3.2.3“为什么第二个方法会比第一个方法好?”第一小点的好处是为了解决直接映射而采取分组（组映射，全关联映射）的好处，第二点三种映射模式都能达到这个要求，不算是好处；且这一部分都是讲直接映射没有看出哪个是“第一种方法”，哪个是“第二种方法”（之前的1小点是直接映射原理,2小点是放置方法，应该不能比较）
  * 2.3.2.6 example “第三位决定块内地址”应为“**低**三位决定块内地址”
  * 2.3.2.8 缺点改为“**对应同一cache行的**两个块被重复使用的话有可能出现**抖动**的现象。”更准确
  * 2.6.1.1“直接映射的命中率是最低的，**组相联映射**的命中率是最高的”翻译有误，应为“直接映射的命中率是最低的，**全关联映射**的命中率是最高的”

* lecture11
  * 2.5.1“Use of an independent access technique(**使用并行访问机器**)”翻译有误，应为“**使用独立访问技术**”
  * 2.6.2 “**不免**可能的I/O瓶颈”可能是“**避免**可能的I/O瓶颈”？

* lecture13
  * 4.1“Arbitration Type(**总裁**类型)” 下文的“Arbitration”翻译都是“**仲裁**”，翻译成“仲裁类型”稍好
  * 5.2.3“如果一个设备需要总线，并且ID和当前的**技术**相同，则仲裁器终止**技术**并且设备设置总线为忙。” 的“技术”都应为“**计数**”
  * 8.1.3.3.1 “读出和读入各1个周期”没看懂这是什么意思，从内存获取前4个字花了200ns（Data read时间），所以Data transfer是数据传输4个字的时间（每个字32位，总线64位，共2个周期），不必分成两部分时间看

* lecture14
  * 6.8.2.4“我写相对开头的位置的偏移量是多少。“，不懂。。。。
  * 8.3 “可**边**长操作码:使得指令一般会相对更加短(如上图)”是“可**变**长操作码:”？

**Comment by stormbroken** [comment]
http://freezer712.top/note_pictures/cpt4_pic1.png%E2%80%9D 链接已失效，此外的问题都已经修改

**Comment by SpriCoder** [comment]
问题均已修改，感谢反馈！
