### ISSUE TITLE
关于数据结构的一些问题

### ISSUE THREAD

**Issue by darielli** [stormbroken/Class-Notes#3]
## 关于数据结构的一些问题

* 数据结构2-递归与迭代
  * 1.1实例后的代码是“**bad**”的示例，放在此处且没有解释容易引起误解，在**1.2要点的第一要点**恰好是说明这点的，因此将那段代码放在1.2的第一小点后更合适
* 数据结构3.2-List
  * 3.4.5的代码倒数第二行    “private int coeffArra y[ ] = new int [**MAX-DEGREE** + 1];”代码中连接应用**_**（下划线）,此处为**-**（减号）

* 数据结构4-Tree
  * 3.7.1**!(img/cpt5/4.png)**没插入图片，应为**![](img/cpt5/4.png)**

* 数据结构5-hashing
  * 1.4 第3点中文解释与英文不对应
* 数据结构8.0-graphs
  * 5.6 Prim算法优化 “img/cpt10/36.png”重复出现了2次，”img/cpt10/37.png“是prim算法的配图，而非优化后算法的配图（PPT上这一部分的配图还有 http://freezer712.top/note_pictures/ds1.jpg http://freezer712.top/note_pictures/ds2.png http://freezer712.top/note_pictures/ds3.png http://freezer712.top/note_pictures/ds4.png http://freezer712.top/note_pictures/ds5.png http://freezer712.top/note_pictures/ds6.png  ，可以考虑替换图37以及重复了的36）
  * 6.1.6. **”进一步思考，就是只进行一步，不进行多不步“** 应该是多打了一个**“不”**字
  * 6.2 edge【v】【u】 由于markdown语法原因显示为**edgev** ，如果可以的话修改一下最好。
  * 7.2  2.顶点 字母后数字应该为下标（不修改也不影响意思表达，可以看懂）

**Comment by SpriCoder** [comment]
感谢你的发现，我已经修改了对应部分的错误
